language: node_js
node_js:
- '0.12'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ykBnridyVP1iRpgHlE8L9192V5+xZYWw+n3FaRlvy0EJJV3BlNwC+4aVn/sRJllx22Q8If35u6l9J7MxeO7KTK90omFhrlvCLGEB45Sz69DV2k4FJVopqzfgRSjZ1Bn5XFUzHtpYaW3fOQ0Af7ppHyM/WlUh8VeI14zkvzEpfjjcMx9elmeRAKRSnB5Dk//pk1PDBE2BiNVjho3fNgc3mrZZznBcTqgGR4GPp28IBB8+pcxiJ5Ko2b13QdUo5lIPTVn7sHprkp5e09qX0MPonx4eA5uK04YXnydGIpe6uY4OiWrGmKD1Hs950UJy9n3kYlRy3SmQ4ZK4ME4x96aDpw6M29c9Vy9NkfH4rlAS6jAajpccRJCpBD/TwBD+YgEupjIrkpoQlKTRcoOrMk8+hfv9zEMMrZ+jaTd4JhTcHtzfLrpRS19FlQALy37xm73Sk/Jao/jzT7goRtDS7T2bwX8zUThcqcX9BoI7sh5MqpEnxDSXHlTYFPw57aHlsRAMubEWIgmbD/Kj7mgjO8AL0rIPDL5WxFrhB8oMI8gm7q8BwFhI6IDCStOlUjY01uN+gz4jnNGsZCANYsQVXjNoRnaYGp/J2/F5dIKEBeBF+J+xPhCqgoa118IzfBnKrQObTMIv4ecfrYNFHJI8x8eGqqXi3PXLW7wTpd+HdtDEA3k=
  app:
    master: teamtrycatch
    dev: devtrycatch
  buildpack: https://github.com/AdmitHub/meteor-buildpack-horse.git
notifications:
  slack:
    secure: DXANfJgS656O7Dbkkv88k1N8fG7TF8W8UZFy++GZ8h5w4ocJlXjiPSVZOUH0antMp9EJcZn7j0mFoZqlXMXDM5ZzAAnapH2umhYr9ZrJ2K4A5ckyZuXBTIiYIlqUCLVjekwZWun2Vo3f8m1xPECleBvPOfrlj8Hp1U1tEHcLDMhckdhsPperf3XSkZuZPDOXc5JZot5MCKuHny1sz0AtAGVBV4/lwNh3P8n6Nft6D+ylf+kDJ4bViMAUA2jSQs7+dUkipuDMurVjU42UJa2eab9x29FxMeHq+I9zk9aR4OnaFJX+ka9089zKo0vXfZn50yziRcc/l8t5wTTXRYhsEK6ACzul7aCa9h9HFnX8jjwypxWjwNxSAMNDsbfgUyIri4gKntKeOcWLfa3ekERSFX4PQJnPr9m6T3EStqS40RDB2KuA8UFUjBYgQpOSWvjEERN3iV0upCu5uJLrRCAbyFNDqcIhg6PvTi2QhkcI7FmT2FC5/4taScX0qKXFxblfKB7SCTM83eZxoEyGGLnWv8bhetHIj4DO89mZIypmvi/NphMqUOMeHWyvTZ/0k2GzM8+B+VuEUJGLm0DzTNmK/C3zwj1pRrjj0f2z+G8obJwStf2fqk4mChccEi6YZZIAb2FF0zMsbdWm7AD17SHPqMD7FtE0zVuFKekdX4NyOx8=
